packages:
  - apps/*
  - services/event-crawler
  - services/ticket-crawler
  - com.intheloopstudio/functions
  - packages/*

ignoredBuiltDependencies:
  - jpegtran-bin
  - nodemailer

onlyBuiltDependencies:
  - '@firebase/util'
  - core-js
  - esbuild
  - protobufjs
  - puppeteer
  - sharp
