name: intheloopapp
version: 1.2.115+127
publish_to: none
description: mobile app for tapped.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  algolia: 1.1.2
  animations: 2.0.11
  app_settings: ^6.1.1
  avatar_stack: 3.0.0
  badges: 3.1.2
  bloc: 9.0.0
  bloc_test: 10.0.0
  cached: ^1.7.1
  cached_annotation: ^1.7.1
  cached_network_image: ^3.4.1
  cancelable_retry: 0.1.0+1
  card_banner: 0.0.1+2
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  confetti: 0.8.0
  crypto: 3.0.6
  cupertino_icons: 1.0.8
  currency_text_input_formatter: ^2.2.8
  email_validator: 3.0.0
  enum_to_string: ^2.2.1
  equatable: 2.0.7
  feedback: ^3.2.0
  file_picker: ^10.3.1
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_crashlytics: ^5.0.0
  firebase_in_app_messaging: ^0.9.0
  firebase_messaging: ^16.0.0
  firebase_performance: ^0.11.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
  flutter: 
    sdk: flutter
  flutter_app_badger: 1.5.0
  flutter_bloc: ^9.1.1
  flutter_cache_manager: 3.4.1
  flutter_easyloading: 3.0.5
  flutter_google_places_sdk: ^0.4.0
  flutter_image_compress: ^2.4.0
  flutter_map: 7.0.2
  flutter_map_heatmap: 0.0.8
  flutter_map_marker_cluster: 1.4.0
  flutter_map_tile_caching: 10.0.0
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: 4.0.1
  flutter_slidable: 4.0.0
  flutter_spinkit: ^5.2.2
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  formz: 0.8.0
  fpdart: 1.1.1
  freezed_annotation: 2.4.4
  gallery_saver: 2.3.2
  gauge_indicator: 0.4.3
  geolocator: ^14.0.2
  georange: 1.0.0
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  group_radio_button: 1.3.0
  hydrated_bloc: ^10.1.1
  image_downloader:  # 0.31.0
    git:
      url: https://github.com/ko2ic/image_downloader.git
  image_gallery_saver: 2.0.3
  image_picker: 1.1.2
  intl: ^0.20.2
  isar_flutter_libs: 3.1.0+1
  json_annotation: 4.9.0
  linkify: 5.0.0
  logging: 1.3.0
  maps_launcher: 3.0.0+1
  mime: ^2.0.0
#  modal_bottom_sheet:
#    git:
#      url: https://github.com/jamesblasco/modal_bottom_sheet
#      path: modal_bottom_sheet
  multi_select_flutter: 4.1.3
  package_info_plus: ^8.3.1
  path: 1.9.1
  path_provider: 2.1.5
  permission_handler: ^12.0.1
  photo_view: 0.15.0
  pull_down_button: 0.10.2
  purchases_flutter: ^9.2.1
  quiver: 3.2.2
  readmore: 3.0.0
  rive: 0.13.20
  rxdart: ^0.28.0
  scroll_snap_list: 0.9.1
  share_plus: ^11.1.0
  sign_in_with_apple: ^7.0.1
  skeleton_animation: 0.1.4
  skeleton_text: 3.0.1
#  skeletons: 0.0.3
  skeletons:
    git:
      url: https://github.com/makslara/skeletons
      ref: fix-path-apptheme
  stack_trace: 1.12.1
#  stream_chat_flutter:
#    git:
#      url: https://github.com/easyhour/stream-chat-flutter
#      path: packages/stream_chat_flutter
#      ref: beta
  stream_chat_flutter: ^9.16.0
#  stream_video_flutter: 0.3.1
  timeago: ^3.7.1
  timelines: 0.1.0
  transparent_pointer: 1.0.1
  app_links: ^6.4.1
  upgrader: ^11.5.0
  url_launcher: ^6.3.2
  uuid: 4.2.1
  visibility_detector: 0.4.0+2
  modal_bottom_sheet: 3.0.0
  screenshot: 3.0.0
  qr_flutter: 4.1.0
  dio: ^5.9.0
  lucide_icons: 0.257.0
  posthog_flutter: ^5.3.1

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.3.1
  mockito: ^5.0.16
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^9.0.0

dependency_overrides:
  audio_video_progress_bar: 2.0.3
  http: 0.13.3
  uuid: 4.2.1
  photo_manager: 3.0.0

flutter_icons: 
  image_path_ios: assets/app_icon_ios.png
#  image_path_android: assets/app_icon_ios.png
#  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/cities/
    - assets/layers/
    - assets/default_images/
  uses-material-design: true
