# Venue Enrichment Configuration

[blocklist]
# Domains to exclude from scraping
domains = [
    "facebook.com",
    "instagram.com", 
    "linkedin.com",
    "pinterest.com",
    "reddit.com",
    "youtube.com",
    "twitter.com",
    "tiktok.com",
    "snapchat.com"
]

[scraping]
# Maximum crawl depth for each website
max_depth = 2

# Maximum number of pages to scrape per website
max_pages_per_site = 5

# HTTP timeout in seconds
timeout_seconds = 30

# Respect robots.txt files
respect_robots_txt = true

# List of user agents to rotate between
user_agents = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
]

[agent]
# Maximum number of venues to process concurrently
max_concurrent_venues = 3

# Maximum number of websites to scrape concurrently per venue
max_concurrent_scrapes = 5

# Number of retry attempts for failed operations
retry_attempts = 3

# Delay between retry attempts in seconds
retry_delay_seconds = 2

[rate_limiting]
# Maximum requests per second
requests_per_second = 2.0

# Maximum burst size for requests
burst_size = 5

# Minimum delay between requests in milliseconds
delay_between_requests_ms = 500

# Example proxy configuration (uncomment to use)
# [proxy]
# http_proxy = "http://proxy.example.com:8080"
# https_proxy = "https://proxy.example.com:8080"

# Example API configuration (these can also be set via environment variables)
# [api]
# exa_api_key = "your-exa-api-key-here"
# llm_api_key = "your-openai-api-key-here"
# llm_base_url = "https://api.openai.com/v1"
# llm_model = "gpt-3.5-turbo"