import { Timestamp } from "firebase-admin/firestore";
import { Booking, EventData, UserModel } from "../types.js";
import { db } from "./firebase.js";
import { getBaseDomain } from "./parsing.js";

const crawlerRef = db.collection("crawler");
const usersRef = db.collection("users");
const bookingsRef = db.collection("bookings");

export function getVenueUsernameChunk(): string[] {
  const initVenueUsernames = [
    // Legacy scrapers from webscrapers project (all 10 scrapers)
    // "thejungleroom",
    // "goldenpony",
    // "ember_music_hall",
    // "wonderville",
    // "pearl_street_warehouse",
    // "songbyrd_music_house",
    // "brooklyn_made",
    // "comet_ping_pong",
    // "nighthorse",
    // "the_old_town_pub",
    // "club_aqua_tampa",
    // "99_bottles",
    // "icebar_orlando",
    // "bellhop_orlando",
    // "killington_distillery",
    // "1800lucky",
    // "basement_miami",
    // "museum_of_arts__sciences",
    // "grind_gastropub",
    // "the_venue_fort_lauderdale",
    // "the_geek_easy",
    // "schooners_last_local_beach_club",
    // "skippers_smokehouse",
    // "jax_food__games",
    // "holiday_inn_resort_panama_city_beach",
    // "mastrys",
    // "siesta_key_oyster_bar",
    // "southside_steakhouse",
    // "charlie_park",
    // "bamboo_willies_beachside_bar",
    // "ciros_speakeasy_and_supper_club",
    // "1st_republic_brewing",
    // "caseys_caboose",
    // "vermont_tap_house",
    // "bin_39_wine_bar",
    // "the_tree_bar",
    // "woodstock_town_hall",
    // "the_sea_bar",
    // "backbooth",
    // "renegades_country_bar__grill",
    // "miami_improv_comedy_club",
    // "st_augustine_distillery",
    // "the_palladium_theater",
    // "calusa_brewing",
    // "the_loft",
    // "mynt_lounge",
    // "jaguar_sun_mia",
    // "hogs_breath_saloon",
    // "sharkys_beachfront_restaurant",
    // "the_atlantic",
    // "the_craft_bar__destin",
    // "wall_st_plaza",
    // "camelot",
    // "river_roost_brewery",
    // "beaches_daytona",
    // "edison_restaurant_ft_myers",
    // "better_days",
    // "kingdom_brewing",
    // "brickell_city_centre",
    // "doc_ponds",
    // "bradleys_on_7th",
    // "gilligans_island_bar",
    // "macdintons_irish_pub",
    // "the_brass_tap",
    // "the_ben_autograph_collection",
    // "superette",
    // "odd_birds_cocktail_lounge_and_kitchen",
    // "qxts_night_club",
    // "the_kessler",
    // "uries_waterfront_restaurant",
    // "departed_soles_brewing_company",
    // "garden_of_eden",
    // "the_fat_tuscan_cafe",
    // "potbellys",
    // "the_wharf_miami",
    // "the_doctors_office",
    // "forgotten_tonic",
    // "pegasus_lounge",
    // "the_regent_cocktail_club",
    // "the_citadel",
    // "red_rock_tap__grill",
    // "chupitos",
    // "the_bends",
    // "margaritaville_panama_city_beach",
    // "the_poorhouse",
    // "floyd_miami",
    // "czar",
    // "art_ovation_hotel",
    // "silver_q_billiards__sports_bar",
    // "the_bait_house",
    // "riverhouse_waterfront_restaurant",
    // "sistrunk_marketplace__brewery",
    // "salty_dog",
    // "donovans_reef_bar",
    // "the_todd_herendeen_theatre",
    // "saltys_island_bar__grille",
    // "petes_bar",
    // "roque_pub",
    // "osheas_irish_pub",
    // "roots_the_restaurant",
    // "okemo_mountain_resort",
    // "the_liq",
    // "taco_fresco",
    // "yard_house",
    // "seasons_restaurant",
    // "wicked_cantina_sarasota",
    // "the_corner_miami",
    // "cooters",
    // "margaritaville",
    // "elisabettas_ristorante_bar_pizzeria",
    // "hyde_beach",
    // "citizen_dallas",
    // "saints_and_sinners_pub",
    // "mangos_tropical_cafe_south_beach",
    // "southern_nights",
    // "peter_shields_inn__restaurant",
    // "hg_supply_rooftop",
    // "courtyard_hanover_lebanon",
    // "clevelander",
    // "raymond_f_kravis_center_for_the_performing_arts",
    // "costantinos_venda_bar__ristorante",
    // "lizzy_mccormacks_irish_pub",
    // "first_chance_last_chance_bar",
    // "stage_7__karaoke__lounge",
    // "eve_on_adams",
    // "zoeys_double_hex",
    // "bar_louie",
    // "old_town_tavern_and_beer_garden",
    // "the_tavern_on_1st",
    // "plugin_karaoke",
    // "singletons_seafood_shack",
    // "mojo_old_city_bbq",
    // "flynn_theater",
    // "on_the_rocks_bar",
    // "gen_x_tavern",
    // "batch_new_southern_kitchen__tap",
    // "10_twenty_five",
    // "infowhiteroomweddingscom",
    // "the_port_tavern_bar_and_grill",
    // "racket",
    // "vida_garden",
    // "lulus_destin",
    // "savoy_orlando",
    // "bo_diddley_plaza",
    // "booby_trap_on_the_river",
    // "the_alibi_beach_lounge_and_grill",
    // "the_speakeasy_inn_and_rum_bar",
    // "the_brandon_inn",
    // "strikes_cigar_lounge",
    // "island_wing_company_grill__bar",
    // "hildene_the_lincoln_family_home",
    // "medium_cool",
    // "maximum_magic_theater",
    // "the_salty_goat_saloon",
    // "the_manor_complex",
    // "boca_black_box",
    // "cantina_aejo",
    // "hijinks_sports_grill",
    // "the_florida_theatre",
    // "the_funky_biscuit",
    // "tipsy_alchemist",
    // "sneakers_bistro",
    // "komodo_lounge",
    // "the_ice_plant",
    // "byblos_miami",
    // "blue_martini",
    // "mai_tai_bar",
    // "the_rum_runner",
    // "aromas_cigar__wine_bar",
    // "izzys_fish__oyster",
    // "mountain_meadows_lodge",
    // "river__fort",
    // "selva_grill",
    // "capones_night_club",
    // "city_tavern",
    // "harolds_coffee_lounge",
    // "ajs_club_bimini",
    // "cidercade_dallas",
    // "palace_bar__restaurant",
    // "hooch_and_hive",
    // "club_la",
    // "sway_nightclub",
    // "giselle_miami",
    // "schooner_wharf_bar",
    // "breezy_jazz_house__restaurant",
    // "the_bark",
    // "cocktails__screams",
    // "shephards_tiki_beach_bar_and_grill",
    // "new_world_tampa",
    // "beacon_social_drinkery",
    // "centro_wynwood",
    // "stardust_lounge",
    // "americas_backyard",
    // "florabama_lounge__package",
    // "tangra_nightclub",
    // "the_adderley_amphitheater",
    // "foxs_lounge",
    // "sidebar_caf",
    // "the_legendary_boot_hill_saloon",
    // "brewsters_gastropub",
    // "inn_at_pleasant_lake",
    // "tootsies_orchid_lounge_panama_city_beach",
    // "lost_weekend",
    // "rockwell_miami",
    // "el_patio_wynwood",
    // "spruce_performing_arts_center",
    // "west_end_pub",
    // "boathouse_oyster_bar_and_grill",
    // "kimpton_taconic_hotel",
    // "el_meson_de_pepe",
    // "mcgraths_irish_pub",
    // "atlantic_city_convention_center",
    // "alexis__jim_pugh_theater",
    // "restaurant_iron",
    // "bar_bevy_miami",
    // "the_irishmen",
    // "vivid_music_hall",
    // "jimmys_fish_house",
    // "last_resort_bar",
    // "the_red_cadillac",
    // "blue_bamboo_center_for_the_arts",
    // "skunk_hollow_tavern",
    // "eve_orlando",
    // "tenn_nightclub",
    // "state_street_srq",
    // "trailside_inn",
    // "coconut_charlies_beach_bar__grill",
    // "hot_spot_barbecue",
    // "crafty_squirrel",
    // "night_swim_rooftop_bar",
    // "bayfront_park_amphitheater",
    // "raffurtys_bar_and_grill",
    // "velvet_gypsy",
    // "copper_blues_rock_pub__kitchen",
    // "maxs_grille",
    // "the_commodore_coconut_grove",
    // "robbie_oconnells_pub",
    // "lil_rudys",
    // "cafe_davinci",
    // "irish_kevins",
    // "patches_pub_and_grill",
    // "hopn_moose",
    // "wilburton_inn",
    // "deep_brewing_co",
    // "big_fattys",
    // "lookout_killington",
    // "parker_house",
    // "82west_distilling",
    // "tin_roof_orlando",
    // "the_ale_and_the_witch",
    // "la_vie_restaurant",
    // "racings_north_turn",
    // "centrada_cocina__cocktails",
    // "wolf_tree",
    // "champlain_valley_unitarian_universalist_society",
    // "cuba_libre_jax",
    // "the_patio",
    // "ocean_deck",
    // "the_courtesy_bar",
    // "six_26",
    // "hooters",
    // "bar_1903",
    // "the_boardwalk",
    // "the_attic",
    // "the_city_lounge__restaurant",
    // "jaspers_tavern",
    // "rococo_steak",
    // "notte",
    // "marsh_tavern_at_equinox_hotel",
    // "bestbet",
    // "7th__grove",
    // "monty_hall",
    // "stowe_cider",
    // "the_wobbly_barn",
    // "cattle_n_clover",
    // "main_street_museum",
    // "tropezn",
    // "uncle_tonys_vt",
    // "hippodrome_theatre",
    // "cage_brewing",
    // "mangos_tropical_cafe__orlando",
    // "union_underground",
    // "jockey_hollow_bar__kitchen",
    // "cavo_lounge",
    // "floridian_social_club",
    // "mahaffey_theater",
    // "ybor_cigars_plus_lounge",
    // "smokin_tuna_saloon",
    // "pineapple_willys_restaurant",
    // "the_bank",
    // "redds_biergarten_newark",
    // "banko_cantina",
    // "faena_theater",
    // "hard_rock_hotel_daytona_beach",
    // "clematis_social",
    // "dullboy",
    // "liquid_art_coffeehouse_and_eatery",
    // "vault_5421_at_gods_and_monstersv",
    // "myth_nightclub__element_bistro",
    // "angelenas_ristorante_italiano",
    // "aqua_nightclub",
    // "the_pub_naples",
    // "ac_hotel_by_marriott_fort_lauderdale_beach",
    // "the_cottage",
    // "our_house_bistro",
    // "coyote_ugly",
    // "respectable_street",
    // "keg__coin",
    // "ricks_bar",
    // "foley_brothers_beer_garden",
    // "timucua_arts_foundation",
    // "the_keys",
    // "celine_orlando",
    // "honey_pot",
    // "nols_at_the_franklin_events_center",
    // "casa_marinas_penthouse_lounge",
    // "marina_grille",
    // "room_22",
    // "99_restaurants",
    // "red_clover_inn",
    // "frenchys_rockaway_grill",
    // "dantes_hifi",
    // "coffee_butler_amphitheater",
    // "the_bench",
    // "chillers",
    // "twist_ode",
    // "801_bourbon_bar",
    // "crowbarybor",
    // "balls",
    // "gringos_tacos",
    // "the_ritz_ybor",
    // "rumba_island_bar__grill",
    // "silver_fork",
    // "town_hall_theater",
    // "martins",
    // "fire_bettys_arcade_bar",
    // "hampton_inn_white_river_junction",
    // "ocean_deck_restaurant__beach_club",
    // "sage_srq",
    // "the_biergarten",
    // "main_street_station",
    // "tinker_field",
    // "new_jersey_performing_arts_center",
    // "daer_nightclub",
    // "the_hammered_lamb",
    // "the_foundry_at_summit_pond",
    // "macs_club_deuce",
    // "sunken_gardens",
    // "kill_your_idol",
    // "mote_marine_laboratory__aquarium",
    // "oharas_downtown",
    // "sunset_pier",
    // "t_bar_at_hoagies",
    // "gold_rush_cabaret",
    // "the_independent_bar_and_cafe",
    // "vino_wine_bar_and_kitchen",
    // "the_blind_monk",
    // "steel_tie_spirits_company",
    // "rhythm__vine",
    // "senor_frogs_panama_city_beach",
    // "the_archer",
    // "the_whiskey",
    // "hullabaloo",
    // "boat_house_bar__grill",
    // "the_sarasota_modern_a_tribute_portfolio_hotel",
    // "pompano_beach_amphitheater",
    // "bumpas_local_349",
    // "the_addison",
    // "lagniappe_house",
    // "bilheimer_capitol_theatre",
    // "rubys_elixir",
    // "the_fillmore_miami_beach",
    // "union_public_house",
    // "the_shell_factory",
    // "sidecar_gainesville",
    // "zydeco_brew_werks",
    // "loaded",
    // "lower_bar",
    // "edge_rooftop_cocktail_lounge",
    // "the_tiki_house",
    // "caf_la_trova",
    // "ruperts_sports_bar",
    // "dunedin_house_of_beer",
    // "cucina_palm_beach",
    // "the_getaway_grille_and_bar",
    // "m_bird",
    // "the_barley_house",
    // "ember",
    // "the_anderson_miami",
    // "the_bull_and_whistle",
    // "southern_belle",
    // "the_keyhole_bar",
    // "the_ghost",
    // "neons_beach_shack",
    // "war_memorial_auditorium",
    // "gramps",
    // "wills_pub",
    // "el_monsenor_bar",
    // "gringo_jacks",
    // "station_house_st_pete",
    // "hansons_shoe_repair",
    // "healys_tavern",
    // "allgood_cafe",
    // "times_ten_cellar",
    // "the_floridian",
    // "isla__co",
    // "crabs_on_the_beach",
    // "strike_10_bowling",
    // "sloppy_taco_palace",
    // "the_copper_grouse",
    // "the_spring_lake_manor",
    // "ye_olde_tavern",
    // "mandarin_heights",
    // "voltaires_lair",
    // "the_sylvester",
    // "copper_rocket_pub",
    // "sloppy_joes",
    // "casa_de_montecristo",
    // "sidecar_social",
    // "soundbar",
    // "beach_club_siesta_key__1947",
    // "the_ranch_concert_hall__saloon",
    // "rosie_ogradys",
    // "luckys_tavern",
    // "the_plaza_resort__spa",
    // "catch_27",
    // "angelinas_pizzeria",
    // "sarbez",
    // "great_notch_inn",
    // "backyard",
    // "parliament_house",
    // "the_rollin_mullet",
    // "the_blind_tiger_caf",
    // "elixir",
    // "undertow",
    // "edgewater_gallery_at_the_falls",
    // "la_fonda_restaurant",
    // "cask_ale_and_kitchen",
    // "key_west_theater",
    // "the_equinox_golf_resort__spa",
    // "rok_bar",
    // "kickbacks_gastropub",
    // "hard_rock_hotel__casino",
    // "jellyfish_restaurant",
    // "sweet_liberty_drinks__supply_company",
    // "vermont_inn",
    // "mystic_restaurant__bar",
    // "tatum_obrians",
    // "the_stirling_hotel",
    // "926_bar__grill",
    // "brew_garden_taphouse_and_eatery",
    // "american_social_tampa",
    // "the_beach_bucket_bar__grill",
    // "sak_comedy_lab",
    // "blackback_pub",
    // "groove_authority",
    // "backstreets_sports_bar",
    // "harbor_tavern",
    // "jack_flats",
    // "the_bricks",
    // "union_new_american",
    // "root_down_jax",
    // "long_trail_brewing_company",
    // "kapow_noodle_bar",
    // "the_ben_west_palm",
    // "petes_place_south_tampa",
    // "blur_nightclub",
    // "george_bistro__bar",
    // "beacon_tampa",
    // "wicked_wings",
    // "low_fidelity_bar",
    // "captain_curts_crab_and_oyster_bar",
    // "new_deal_cafe",
    // "meliora",
    // "grandview_public_market",
    // "the_village_door",
    // "orlando_improv_comedy_club",
    // "crazy_uncle_mikes",
    // "dirty_harrys",
    // "firefly_restaurant",
    // "215_speakeasy",
    // "orlando_amphitheater",
    // "brick_miami",
    // "the_cliff",
    // "tryst_gastro_lounge",
    // "gateway_cinema",
    // "kinya_ramen",
    // "cowboys_orlando",
    // "e11even_miami",
    // "heartwood_soundstage",
    // "island_dogs_bar",
    // "the_smallest_bar",
    // "aloma_bowling_center",
    // "jannus_live",
    // "vinyl_music_hall",
    // "octopus_garden",
    // "harrisons_restaurant",
    // "salt__spirits",
    // "daltons_sports_grill",
    // "matterhorn_restaurant__nightclub",
    // "parrot_key",
    // "ember_supper_club",
    // "addition_financial_arena",
    // "hotel_coolidge",
    // "pm_lounge",
    // "naples_grande_beach_resort",
    // "proving_ground",
    // "bodega_taqueria_y_tequila",
    // "mount_sunapee_resort",
    // "stache",
    // "phineas_phoggs_bar_in_seville_quarter",
    // "club_prana",
    // "ology_power_mill",
    // "shots_orlando",
    // "double_ds",
    // "hoptinger",
    // "ralph_myhre_golf_course",
    // "museum_of_science__history",
    // "yeomans_road_pub",
    // "1592_wood_fired_kitchen__cocktails",
    // "congaree_and_penn",
    // "the_grand_marlin_of_pensacola_beach",
    // "middlebury_inn",
    // "flying_biscuit_cafe",
    // "longbar_pub__grill",
    // "filling_station",
    // "fords_garage",
    // "blackbird_ordinary",
    // "the_milk_district",
    // "hidden_treasure_tiki_bar__grill",
    // "er_bradleys_saloon",
    // "harrys_seafood_bar__grille",
    // "duffinettis_restaurant_and_lounge",
    // "chart_house",
    // "frying_pan__nyc",
    // "baxters_restaurant_at_rutland_country_club",
    // "universal_citywalk",
    // "reefers_social_club",
    // "lil_indies",
    // "bird_bowl",
    // "durty_harrys",
    // "the_local_662",
    // "the_lucky_lure",
    // "the_hub",
    // "oasis_tiki_bar",
    // "crazy_uncle_mikes",
    // "inn_at_pelican_bay",
    // "liberty_bar",
    // "terra_italian_steakhouse",
    // "club_504",
    // "grape_and_grain_exchange",
    // "zenbarn",
    // "mr_and_mrs_crab",
    // "bricks_nightclub",
    // "hudson_hall",
    // "westin_rooftop",
    // "alfies_wild_ride",
    // "mathers_social_gathering",
    // "boca_luna_luxe_lounge",
    // "the_reef_bar_and_grill",
    // "seminole_hard_rock_hotel__casino__hollywood",
    // "curtis_hixon_waterfront_park",
    // "summit_lodge",
    // "lightner_museum",
    // "punch_room",
    // "laundromat_bar",
    // "level_ii",
    // "cocktail_st_pete",
    // "potts_sports_cafe",
    // "duvals_fresh_local_seafood",
    // "beaver_bar",
    // "blue_heaven",
    // "truman_little_white_house",
    // "mama_tried_bar",
    // "b2_bistro__bar",
    // "roundup_saloon",
    // "aaron_bessant_park",
    // "burts_irish_pub",
    // "vinoy_park",
    // "hyatt_regency_coconut_point_resort__spa",
    // "whiskey_joes",
    // "arcade_bar",
    // "the_shipwreck",
    // "rosie_ogradys_dueling_piano_bar_in_seville_quarter",
    // "the_office_tavern_grill",
    // "the_basement_orlando",
    // "treehouse",
    // "george_steinbrenner_field",
    // "enigma_st_pete",
    // "bourbon_street_pub",
    // "cws_gin_joint",
    // "rockhouse_live_key_west",
    // "sidebar_key_west",
    // "teds_hideaway",
    // "landshark_bar__grill__daytona_beach",
    // "pci_beach_bar_postcard_inn_beach_bar",
    // "tier_nightclub",
    // "chandler_music_hall",
    // "flagler_tavern",
    // "mbird_at_armature_works",
    // "the_lazy_goat_tavern",
    // "the_blue_dog_cookhouse_and_bar",
    // "trulucks_oceans_finest_seafood__crab",
    // "cellar_335",
    // "cold_beer_company",
    // "polynesian_fire",
    // "brandson_the_bayou",
    // "jay_peak_resort",
    // "rivershed",
    // "ellas_americana_folk_art_cafe",
    // "casa_de_vino_57",
    // "station_4_s4",
    // "fish_camp",
    // "the_hangar",
    // "river__post",
    // "hyde_park_cafe",
    // "madison_social",
    // "edgewater_beach__golf_resort",
    // "jacks_by_the_tracks",
    // "little_tijuana_nj",
    // "old_city_pub",
    // "amigos_mexican_restaurant",
    // "teak_restaurant__bar",
    // "famished_frog__legends_sports_bar",
    // "the_premiere_motor_inn",
    // "end_of_elm",
    // "the_robinson_ale_house",
    // "anglesea_pub",
    // "the_lobby",
    // "the_taste_of_brazil_steakhouse",
    // "la_fiamma_restaurant_and_bar",
    // "morristown_game_vault",
    // "first_republic_lounge__restaurant",
    // "tavern_off_the_green",
    // "allure_lounge",
    // "buona_sera_restaurant__bar",
    // "barcode_new_jersey",
    // "peru_taypa",
    // "mcloones_pier_house",
    // "white_star_bar",
    // "red_tank_brewing",
    // "stirling_tavern",
    // "httpswwwfacebookcomlamplighterbrewing",
    // "frankie_eats_jc",
    // "pierogies_house",
    // "asbury_festhalle__biergarten",
    // "dublin_pub",
    // "jamians_food_and_drink",
    // "hops_craft_beer_bar",
    // "keenans_irish_pub",
    // "djais",
    // "the_yard",
    // "the_boondocks_fishery",
    // "pet_shop",
    // "char_steak_house_red_bank",
    // "sabor_unido",
    // "north_end_american_grill",
    // "mercato_tomato_pie",
    // "the_corkscrew_bar__grill",
    // "10th_ave_burrito_co",
    // "shapiros_new_york_delicatessen",
    // "dorrians_red_hand",
    // "johnny_tequilas",
    // "two_mile_landing",
    // "goodnight_irenes",
    // "bar_anticipation",
    // "triumph_brewing_company",
    // "dannys_steakhouse",
    // "beach_haus_brewery",
    // "the_headliner",
    // "dogtooth_bar__grill",
    // "kilkenny_alehouse",
    // "dolphin_inn",
    // "horseshoe_tavern",
    // "don_felix_bar_and_restaurant",
    // "birravino",
    // "stone_house_at_stirling_ridge",
    // "porta_jersey_city",
    // "burkes_tavern",
    // "morristown_unitarian_universalist_fellowship",
    // "morristown_deli",
    // "bellos_pub",
    // "roots_steakhouse",
    // "coastal_blue_oceanside_bar__grill",
    // "sm23",
    // "bistro_46_morristown",
    // "1776_morristown",
    // "dublin_house",
    // "the_tops_diner",
    // "patrizias_of_red_bank",
    // "cj_mcloones_pub_and_grille",
    // "neapoli_red_bank",
    // "johnny_mac_house_of_spirits",
    // "molly_pitcher_inn",
    // "town_bar_and_kitchen",
    // "krugs_tavern",
    // "rewax_and_unwine",
    // "southpine_american_eatery",
    // "mudhen_brewing_company",
    // "the_wharf_nj",
    // "jenks_club",
    // "surfside_west",
    // "the_ashford",
    // "reef__barrel",
    // "the_columns",
    // "the_waterfront_wildwood",
    // "revolution_morristown",
    // "grasshopper_off_the_green",
    // "chef_fredys_table",
    // "boathouse_bar_and_grill",
    // "count_basie_center_for_the_arts",
    // "zeppelin_hall",
    // "sushi_lounge_morristown",
    // "mehndi",
    // "pazzo",
    // "carneys",
    // "ramen_gami",
    // "willow_creek_winery__farm",
    // "world_famous_waiting_room",
    // "blitz_sports_bar",
    // "st_peters_episcopal_church",
    // "waterside_restaurant__catering",
    // "red_bull_arena",
    // "dingbatz",
    // "mcgoverns_tavern",
    // "dismal_harmony_distilling",
    // "kleins_fish_market__waterside_cafe",
    // "46_lounge",
    // "berkeley_oceanfront_hotel",
    // "the_melting_pot",
    // "the_osprey_nightclub",
    // "el_buen_gusto_restaurant_and_bar",
    // "nico_kitchen__bar",
    // "millies_old_world_meatballs__pizza",
    // "tashmoo_restaurant__bar",
    // "madame",
    // "9th_ave_pier",
    // "pig_dog_beach_bar",
    // "nugents_tavern_irish_pub__grill",
    // "rain_or_shine_studios",
    // "kim_maries_eat_n_drink_away",
    // "amanti_vino_morristown",
    // "destino_lounge_and_bar",
    // "anchor_tavern",
    // "saltys_beach_bar",
    // "jimenez_tobacco",
    // "the_jefferson_house",
    // "hobbys_delicatessen__restaurant",
    // "iron_bar",
    // "nicholas_barrel__roost",
    // "south_orange_performing_arts_center",
    // "mcloones_boathouse",
    // "merrill_auditorium",
    // "free_street",
    // "jazzys_cabaret",
    // "bombay_river",
    // "kelseys",
    // "genos_rock_club",
    // "american_flatbread",
    // "the_robinson_ale_house_asbury_park",
    // "bearded_ladys_jewel_box",
    // "white_eagle_hall",
    // "chicken_bone_beach_historical_foundation",
    // ----------------- TODO
    // "kraverie",
    // "the_1000_acres_ranch_resort",
    // "childrens_museum__theatre_of_maine",
    // "tauk_at_trails_end",
    // "echo_leahy_center_for_lake_champlain",
    // "ordinary",
    // "pier_13",
    // "caroline_street_pub",
    // "r_bar__restaurant",
    // "the_iron_whale",
    // "snapdragon_coffee__social",
    // "johnny_mac_house_of_spirits",
    // "shark_bar",
    // "hatties_restaurant",
    // "back_alley_bar__grill",
    // "deal_lake_bar__co",
    // "asbury_park_music_foundation",
    // "fox_and_crow",
    // "10th__willow",
    // -----------------
    // "cookman_creamery",
    // "the_beach_bar",
    // "ruschmeyers",
    // "fox__crow",
    // "battello",
    // "moonstruck",
    // "church_street_tavern",
    // "bond_street_bar",
    // "tennessee_avenue_beer_hall",
    // "duffys_tavern",
    // "the_wave_bar",
    // "muse__the_end",
    // "blyth__burrows",
    // "ria_mar_restaurant__bar",
    // "stockton_university_performing_arts_center", // edu website
    // "guantanamera",
    // "box_63",
    // "the_berkeley_oceanfront_hotel",
    // "asbury_park_roastery",
    // "georgies_bar",
    // "lunch_lobster_roll",
    // "the_wellmont_theater",
    // "lake_george_beach_club",
    // "pizzeria_verit",
    // "the_asbury_park_boardwalk",
    // "thompsons_point",
    // "fort_william_henry_hotel__conference_center",
    // "talulas",
    // "castaway_cafe",
    // "porta",
    // "the_liberty_house_restaurant",
    // "papi",
    // "tsongas_center_at_umass_lowell",
    // "dancing_grain_farm_brewery",
    // "the_bistro_at_red_bank",
    // "the_vue_rooftop_bar__lounge",
    // "the_park_theater",
    // "charles_r_wood_park",
    // "paradise",
    // "rathskeller_on_wharf",
    // "saratoga_arms",
    // "ri_ra_irish_pub",
    // "martells_tiki_bar",
    // "hamlet__ghost",
    // "tim_mcloones_supper_club",
    // "the_lobby_bar",
    // "waterworks_food__drink",
    // "stephen_talkhouse",
    // "the_surf_lodge",
    // "low_dive",
    // "portland_lobster_company",
    // "maine_craft_distilling",
    // "902_brewing_co",
    // "portland_stage",
    // "dusk__caesars",
    // "bw_kafe",
    // "asbury_park_brewery",
    // "dino__harrys_steakhouse",
    // "r_r",
    // "olympias_zorba_music_hall",
    // "westlake_fish_house",
    // "the_graduate_club",
    // "finnegans_pub",
    // "boca_bistro",
    // "the_archives",
    // "the_saint",
    // "druthers",
    // "lake_george_steamboat_company",
    // "westville_music_bowl",
    // "the_farmhouse_tap__grill",
    // "portland_house_of_music__events",
    // "jersey_girl_kitchen",
    // "cork_city_pub",
    // "room_for_improvement",
    // "sunset_drive_in",
    // "bungalow_beach_bar",
    // "the_strand_theater",
    // "absecon_lighthouse",
    // "adirondack_bar_and_grill",
    // "firehouse_12",
    // "watermark",
    // "spa_city_tap__barrel",
    // "higher_ground",
    // "asbury_park_distilling",
    // "landshark_bar__grill",
    // "cafe_nine",
    // "tiki_mojito",
    // "the_hutton",
    // "the_hideaway",
    // "light_club_lamp_shop",
    // "shubert_theatre",
    // "one_longfellow_square",
    // "obica_mozzarella_bar",
    // "gritty_mcduffs",
    // "taco_gordo",
    // "gosmans_dock",
    // "the_watermark",
    // "the_sembrich",
    // "the_empress_hotel",
    // "the_great_lost_bear",
    // "foam_brewers",
    // "gryphons_pub",
    // "the_thirsty_pig",
    // "state_theatre",
    // "vermont_pub__brewery",
    // "offsuit",
    // "bistro_mediterranean__tapas_bar",
    // "prime_at_saratoga_national",
    // "novare_res",
    // "club_vandome",
    // "the_backyard_restaurant",
    // "side_tracks",
    // "arcadia",
    // "asbury_lanes",
    // "the_gig_shack",
    // "the_east_ender",
    // "on_tap_bar__grill",
    // "rosies_restaurant",
    // "168_york_street_cafe",
    // "artsriot",
    // "electric_haze",
    // "elm_city_social",
    // "barcelona_wine_bar",
    // "toyota_oakdale_theatre",
    // "the_wine_thief",
    // "south_edison",
    // "the_asbury_ocean_club",
    // "salivars_clam_and_chowder_house",
    // "fenimores_pub",
    // "navy_beach",
    // "phebes_tavern_and_grill",
    // "empire_live_music__events",
    // "owl_shop_cigar_lounge",
    // "adirondack_pub__brewery",
    // "the_owl_shop",
    // "the_soundbar",
    // "area_four",
    // "leunigs_bistro",
    // "the_berkeley_hotel_bar",
    // "kim_maries_eat_n_drink_away",
    // "anchor_spa",
    // "cocktail_marys",
    // "15_church",
    // "jimmys_italian_restaurant",
    // "bounce_beach_montauk",
    // "main_street_landing",
    // "sun_tiki_studios",
    // "santiagos_cuban_cuisine",
    // "house_of_independents",
    // "bramhall_pub",
    // "inlet_seafood",
    // "the_bond_street_bar",
    // "trattoria_delia",
    // "space_gallery",
    // "artisanal_brew_works",
    // "akes_place",
    // "the_stone_pony",
    // "pacific_standard_tavern",
    // "the_parting_glass",
    // "aprs",
    // "city_winery",
    // "flask_lounge",
    // "the_flatiron_room_nomad",
    // "caffe_lena",
    // "space_ballroom",
    // "black_flannel_brewing__distilling_company",
    // "the_playwright_irish_pub",
    // "citizen_cider",
    // "lynns_hula_hut",
    // "asbury_ale_house",
    // "toads_place",
    // "three_sheets",
    // "the_tipperary_inn",
    // "casablanca_cruises",
    // "radio_bean_coffeehouse",
    // "hooked",
    // "johnny_macs",
    // "the_burlington_whiskey_room",
    // "bayside_bowl",
    // "9_maple_ave",
    // "the_asbury_hotel",
    // "stella_blues",
    // "old_court",
    // "the_rooftop_cabana_bar",
    // "the_ruck",
    // "the_jewel_box",
    // "geronimo_tequila_bar",
    // "college_street_music_hall",
    // "the_night_owl",
    // "munjoy_hill_tavern",
    // "the_126",
    // "nectars",
    // "monkey_house",
    // "aura",
    // "duryeas_lobster_deck",
    // "terminal_110",
    // "switchback_brewing_co",
    // "harveys_restaurant_and_bar",
    // "charlies_bar__kitchen",
    // "the_shagwong_tavern",
    // "bonfire_country_bar",
    // "cantina",
    // "portland_symphony",
    // "the_merc",
    // "andys_old_port_pub",
    // "h0l0",
    // "chaval",
    // "broadway_joes",
    // "colemans_authentic_irish_pub",
    // "albany_berkshire_ballet",
    // "kernys_pub",
    // "the_pony_bar",
    // "funk_n_waffles",
    // "the_village_vanguard",
    // "pearl_street_grill__brewery",
    // "grace__disgrace",
    // "warrenpeace",
    // "the_ragtrader__bo_peep_cocktail_and_highball_store",
    // "shy_bird",
    // "the_capital_burger",
    // "carroll_place",
    // "sobs",
    // "ciao_ciao_disco",
    // "hq2_nightclub_beachclub",
    // "rudys_bar__grill",
    // "hair_of_the_dog_nyc",
    // "miracle_of_science",
    // "laurie_beechman_theatre",
    // "vista_penthouse_ballroom__catering",
    // "washington_square_park_for_outdoor_performances",
    // "bike_bar",
    // "the_cuban_restaurant_and_bar",
    // "chinese_tuxedo",
    // "the_lavaux",
    // "monks_on_the_commons",
    // "sid_golds_request_room",
    // "side_bar",
    // "campbell_apartment",
    // "bar_43",
    // "fraunces_tavern",
    // "eds_elbow_room",
    // "brandys_piano_bar",
    // "resurgence_brewing_company",
    // "el_mariachi_mexican_restaurant__hamilton_street",
    // "uncle_teds",
    // "5th_hammer",
    // "middlesex_lounge",
    // "the_sefton",
    // "logans_alley",
    // "the_parlour",
    // "jm_curley",
    // "sobs",
    // "ithaca_beer_company",
    // "1_oak",
    // "twigs_lounge",
    // "montage_music_hall",
    // "myrtle",
    // "cantina_rooftop",
    // "flour_city_brewers_fest",
    // "saint_andrews_hall",
    // "gugu_room",
    // "the_york",
    // "slinte_bar_and_lounge",
    // "jules_on_devonshire",
    // "lolita_cocina__tequila_bar_back_bay",
    // "risotto",
    // "icon_bar",
    // "nicks_cigars__vc_cigars",
    // "the_bar_room_at_the_modern",
    // "anthology",
    // "allen_street_pub",
    // "koji_club",
    // "the_stewed_cow",
    // "il_falco",
    // "lone_star_taco_bar",
    // "buffalo_tap_house",
    // "undercote",
    // "pencil_factory",
    // "warp__weft",
    // "kings_dining__entertainment",
    // "barsky_gallery",
    // "kodak_center_for_the_performing_arts",
    // "the_druid",
    // "therapy_lounge_nyc",
    // "ulysses_folk_house",
    // "the_olde_english_pub_and_pantry",
    // "ophelia_ny",
    // "babeville",
    // "storyville_entertainment_complex",
    // "analogue",
    // "fte_music_hall",
    // "jimmy_soho",
    // "dante_nyc",
    // "pokito",
    // "colosseum_providence",
    // "lux_lounge",
    // "the_garret",
    // "needle__thread",
    // "mister_goodbar",
    // "becketts_bar__grill",
    // "dear_irving_gramercy",
    // "redhouse_arts_center",
    // "toro_loco",
    // "mixx_360",
    // "park_playhouse",
    // "brass_bar__lounge",
    // "sulmona_restaurant",
    // "gabriela",
    // "village_underground",
    // "the_greats_of_craft",
    // "geva_theatre_center",
    // "state_theatre_of_ithaca",
    // "bijou_nightclub__lounge",
    // "tinys__the_bar_upstairs",
    // "double_chicken_please",
    // "a4cade",
    // "turks_inn",
    // "club_passim",
    // "100",
    // "half_pint_pub",
    // "ars_nova_theater",
    // "the_mean_fiddler",
    // "manderley_bar",
    // "roar",
    // "maxwells",
    // "the_grand_vin",
    // "the_queens_cups",
    // "stratus_bar_at_view_boston",
    // "shays",
    // "city_swiggers",
    // "vinyl_night_club",
    // "bar_moga",
    // "the_bell_in_hand",
    // "bin_14",
    // "king_of_clubs",
    // "easy_entertaining_inc",
    // "cafe_wha",
    // "the_flower_shop",
    // "off_the_wagon",
    // "city_bistro_restaurant_lounge_bar",
    // "regattabar_jazz_club",
    // "alberts_bar",
    // "melodys_piano_bar",
    // "deep_ellum",
    // "electric_avenue_cafe",
    // "lincontro_by_rocco",
    // "sumiao_hunan_kitchen",
    // "antique_garage_soho",
    // "tanner_smiths",
    // "landmark_tavern",
    // "the_fitz",
    // "warren_tavern",
    // "bondurants",
    // "federal_taphouse__kitchen",
    // "matinee",
    // "albany_capital_center",
    // "the_commodore",
    // "the_uncommons",
    // "mudville9",
    // "gene_mccarthys_old_first_ward_brewing_company",
    // "playerz_zone",
    // "the_strand_ballroom__theatre",
    // "pressroom_pub",
    // "gold_sounds_bar",
    // "skyline_at_waterplace",
    // "124_old_rabbit_club",
    // "mohawk_place",
    // "boch_center_shubert_theatre",
    // "hotel_delmano",
    // "society_of_illustrators",
    // "la_esquina",
    // "el_potro_mexican_grill",
    // "state_park",
    // "raines_law_room",
    // "biergarten_at_the_hollow_bar__kitchen",
    // "syracuse_stage",
    // "austrian_cultural_forum",
    // "finback_lic",
    // "glass_house",
    // "bungalo_lounge_bar",
    // "artevino_studio",
    // "ottos_shrunken_head",
    // "soho_burger_bar",
    // "culture_lab",
    // "mill_city_ballroom",
    // "gran_morsi",
    // "buddakan",
    // "gallow_green",
    // "bonnie_vee",
    // "antique_bar__bakery",
    // "faces__names",
    // "plough__stars",
    // "lamplighterbrewing",
    // "boardwalk_hall",
    // "wild_wills_saloon",
    // "vig_bar",
    // "gola_osteria",
    // "olio_e_pi",
    // "bay_state_brewery__taproom",
    // "wolffs_biergarten",
    // "the_fort",
    // "agency_of_record",
    // "flaming_saddles_saloon",
    // "cookshop",
    // "backbar",
    // "margaritas_after_dark",
    // "the_foundry",
    // "coles",
    // "alto_cinco",
    // "the_elgin",
    // "jungle_bird",
    // "lovin_cup",
    // "stingray_lounge",
    // "the_lexington",
    // "reclamation_bar",
    // "keys__heels",
    // "we_got_company",
    // "bostonia_public_house",
    // "the_inkwell",
    // "blue_ribbon_sushi_izakaya",
    // "manray",
    // "brooklyn_bowl",
    // "sidelines_sports_bar_and_grill",
    // "pj_clarkes",
    // "lobby_bar",
    // "tallyho",
    // "storyville_boston_nightclub",
    // "the_mermaid_inn",
    // "929_lic",
    // "refinery_rooftop",
    // "caledonia_bar",
    // "mezzo_lounge",
    // "magic_hour_rooftop_bar__lounge",
    // "albany_symphony_youth_orchestra",
    // "kind_regards",
    // "company_xiv",
    // "pulqueria_restaurant__agave_bar",
    // "smalls_jazz_club",
    // "drom",
    // "the_excelsior_pub",
    // "rh_rooftop_restaurant_new_york",
    // "munich_haus",
    // "the_stonewall_inn",
    // "bernunzio_uptown_music",
    // "mamalehs_delicatessen",
    // "the_full_shilling",
    // "mezzrow",
    // "blarney_stone",
    // "eddie_bradys",
    // "askew",
    // "gilded_club",
    // "bar_argos",
    // "spring_lounge",
    // "marshall_street_bar__grill",
    // "carla",
    // "waterworks_pub",
    // "tribeca_grill",
    // "bemelmans_bar_at_the_carlyle",
    // "good_luck_restaurant",
    // "focal_point_beer",
    // "omen_azen",
    // "bar_belly",
    // "miller_auditorium",
    // "basement_ny",
    // "comic_strip_live",
    // "pier_17",
    // "w_xyz_lounge",
    // "mojos_dueling_piano_bar__restaurant",
    // "ithaca_bakery",
    // "blue_bull_tavern",
    // "vapor_night_club",
    // "schilling_restaurant__bar",
    // "the_blue_shamrock",
    // "rochester_main_street_armory",
    // "mr_goodbar",
    // "the_penrose",
    // "clinton_street_pub",
    // "als_wine__whiskey_lounge",
    // "apotheke",
    // "the_stewed_cow_saloon",
    // "hochstein_performance_hall",
    // "radegast_hall",
    // "lily_pad_concert_hall",
    // "the_reading_room",
    // "the_beer_market",
    // "the_loft_266_bar__lounge",
    // "pier_26__hudson_river_park",
    // "the_blarney_stone",
    // "the_old_toad",
    // "16_ellicott_bar_and_grill",
    // "down_boston",
    // "brue_bar",
    // "clover_food_lab",
    // "five_mile_stone",
    // "uptown_food__spirits",
    // "99_brick_oven_bar__grille",
    // "bandits",
    // "peachys",
    // "steel__wire",
    // "the_playhouse_swillburger",
    // "elizabeth_of_portofinos",
    // "musica_nyc",
    // "bar_goto",
    // "the_jazz_gallery",
    // "bukowski_tavern",
    // "proctors_theatre",
    // "plough_and_stars",
    // "bar_bantam",
    // "reds_place",
    // "the_scotch_house_pub",
    // "kalamazoo_state_theatre",
    // "louise__jerrys",
    // "gin_rickeys",
    // "shaughnessys_irish_pub",
    // "bua",
    // "the_sinclair",
    // "pinto_garden",
    // "le_poisson_rouge",
    // "scullers_jazz_club",
    // "lullaby",
    // "gansevoort_rooftop",
    // "town_ballroom",
    // "the_dive_barthe_sundown",
    // "the_madison_bar__grill",
    // "fuze_box",
    // "the_black_rose",
    // "angry_garlic",
    // "rec_room",
    // "rochester_international_jazz_festival",
    // "310_bowery_bar",
    // "bar_veloce",
    // "willie_mcbrides",
    // "left_hand_path",
    // "maries_crisis_cafe",
    // "the_skylark",
    // "three_lives",
    // "the_office",
    // "one_restaurant__lounge",
    // "the_wicked_wolf_tavern",
    // "the_village_underground",
    // "gimme_coffee",
    // "albany_symphony_chorus",
    // "dorlans_tavern__oyster_bar",
    // "layali_providence",
    // "ithaca_social",
    // "the_city_beer_hall",
    // "chanticleer",
    // "storyville_entertainment_venue",
    // "1818_bar_and_grill",
    // "the_raven_pub",
    // "basik",
    // "the_malt_house_greenwich_village",
    // "record_room",
    // "split_eights",
    // "joyface",
    // "the_old_stone_tavern",
    // "soho_cigar_bar",
    // "house_of_que",
    // "moonies_bar__nightclub",
    // "the_tippler",
    // "avvino",
    // "farmacia",
    // "the_ten_bells",
    // "orpheum_theatre",
    // "paradise_lost",
    // "the_gibson",
    // "columbus_theatre",
    // "cedar_local",
    // "lager_house",
    // "putnam_den",
    // "holywater",
    // "the_little_whiskey",
    // "revelry_yards",
    // "palma",
    // "victory_cafe",
    // "sojuba",
    // "maison_premiere",
    // "nibsys_pub",
    // "liquid_state_brewing_company",
    // "loulou",
    // "argyle_grill_at_eagle_vale",
    // "pianos",
    // "regattabar",
    // "longfellow_bar",
    // "mr_melo",
    // "common_pub__grille",
    // "trinas_starlite_lounge",
    // "overlook_nyc",
    // "the_point",
    // "cohoes_music_hall",
    // "the_duplex",
    // "carpe_diem",
    // "the_flatiron_room_murray_hill",
    // "theodores_booze_blues__bbq",
    // "south_end_buttery",
    // "royale_boston",
    // "steel_and_wire_cocktail_lounge",
    // "five__dime_coffee__cocktails",
    // "juniors_bar_and_grill",
    // "the_olde_english_pub",
    // "ralphs_chadwick_square_diner",
    // "margaritaville__atlantic_city",
    // "mercato_bar__kitchen",
    // "fire_gypsy",
    // "the_fish_friar",
    // "the_dl",
    // "sweet__vicious",
    // "clandestino",
    // "crown_night_club",
    // "paragon_broadway",
    // "limerick_pub",
    // "hangar_theatre",
    // "old_fashion_cafe",
    // "lost__found_bar__kitchen",
    // "the_raines_law_room",
    // "union_pub",
    // "mehanata",
    // "metrograph",
    // "tap_sports_bar",
    // "birch_hoboken",
    // "adriennes_pizzabar",
    // "noir_cambridge",
    // "oncenter_war_memorial_arena",
    // "dont_tell_mama",
    // "rochester_fringe_festival",
    // "wet_willies_atlantic_city",
    // "the_irish_american_pub",
    // "ego_providence",
    // "lucky_day_whiskey_bar",
    // "dutch_kills",
    // "state_st_pub",
    // "the_f_shed",
    // "prosecco",
    // "adoro_lei",
    // "roxy_bar",
    // "142_sullivan_bar",
    // "ithaca_farmers_market",
    // "the_evergreen",
    // "bloomfields_pub",
    // "casita_del_polaris",
    // "the_estate_boston",
    // "savoy_taproom",
    // "bug_jar",
    // "baker_street_irregulars",
    // "mermaid_oyster_bar",
    // "verlaine",
    // "weather_up",
    // "big_ditch_brewing_company",
    // "sleepwalk_nyc",
    // "jake_hafners_restaurant__tavern",
    // "proletariat_ny",
    // "the_boynton_restaurant__spirits",
    // "ithaca_farmers_market_beer_garden",
    // "grafton_street",
    // "joes_shanghai",
    // "catalyst_restaurant",
    // "pera_soho",
    // "silky_jones",
    // "the_monster",
    // "toad_cambridge",
    // "42_north_brewing_company",
    // "flour_bakery__cafe",
    // "tunnel_boston",
    // "rochester_beer_and_park",
    // "greenwich_street_tavern",
    // "empire_live",
    // "space_billiard_pool_hall__sports_bar",
    // "pazza_notte",
    // "r_lounge_at_two_times_square",
    // "ornithology_jazz_club",
    // "moosewood_restaurant",
    // "white_lion_brewing_company",
    // "the_alley_cat",
    // "hong_kong_restaurant",
    // "moonflower",
    // "amarena",
    // "nietzsches",
    // "alchemy_providence",
    // "pulqueria_blue_agave",
    // "3gs_sports_bar",
    // "the_auction_house",
    // "lure_fishbar",
    // "jones_wood_foundry",
    // "deweys_lounge",
    // "skyz_the_limit",
    // "havana_social",
    // "buffalo_distilling_company",
    // "porchlight",
    // "havana_club",
    // "abilene_bar__lounge",
    // "naco_taco",
    // "one_eleven_chop_house",
    // "drom",
    // "the_django",
    // "jacksons_eatery_bar",
    // "la_compagnie_des_vins_surnaturels",
    // "cantab_lounge",
    // "bottoms_up",
    // "smoke_shop_bbq",
    // "zinc_bar",
    // "rooftop_at_the_providence_g",
    // "the_flatiron_room_nomad",
    // "the_mulberry",
    // "ithaca_ale_house",
    // "club_caf",
    // "the_lot_radio",
    // "city_line_bar_and_grill",
    // "the_watershed",
    // "worthen_house_cafe",
    // "desert_5_spot",
    // "brooklyn_winery",
    // "mace_new_york",
    // "bickering_twins",
    // "mothers_ruin",
    // "lic_bar",
    // "superior_ingredients",
    // "attaboy",
    // "ilili_restaurant",
    // "colored_musicians_club",
    // "the_shepherd__the_knucklehead",
    // "the_fix_burger_bar",
    // "capital_repertory_theatre",
    // "morans",
    // "harro_east_ballroom",
    // "the_white_eagle",
    // "the_range",
    // "ear_inn",
    // "the_443_social_club",
    // "black_bear_bar_grill",
    // "mulberry_street_bar",
    // "landmark_theatre",
    // "joe__the_juice_for_music_ambiance",
    // "stk_steakhouse_downtown_nyc",
    // "nathan_bills_bar__restauran",
    // "monk_mcginns",
    // "the_student_prince_cafe",
    // "radegast_hall__biergarten",
    // "nom_wah_tea_parlor",
    // "tradesman",
    // "albany_pro_musica",
    // "delux_caf",
    // "warsaw",
    // "the_eddy",
    // "red_sorghum",
    // "concept_6",
    // "the_delancey",
    // "the_big_e",
    // "knitting_factory",
    // "crown_shy",
    // "phoenix_landing",
    // "arthurs_tavern",
    // "the_rookery_bar",
    // "sager_beer_works",
    // "the_cave",
    // "ds_keys",
    // "kismet_improv",
    // "german_house",
    // "howl_at_the_moon",
    // "crouse_hinds_theater",
    // "the_middlesex",
    // "green_rock_tap__grill",
    // "the_egg",
    // "the_hollow_bar__kitchen",
    // "cobblestones_restaurant",
    // "rooftop_reds",
    // "lot_10",
    // "trst",
    // "angels_share",
    // "the_odeon",
    // "the_avery",
    // "water_street_music_hall",
    // "butterfly_soho",
    // "paradise_rock_club",
    // "art_bar",
    // "macao_trading_company",
    // "one_nightclub",
    // "vinology__restaurant_bar__event",
    // "the_linda_wamcs_performing_arts_studio",
    // "providence_performing_arts_center",
    // "tremonte_pizzeria",
    // "ithaca_guitar_works",
    // "lark_tavern",
    // "ifc_center",
    // "the_ainsworth",
    // "margaritaville__syracuse",
    // "tally_ho_gentlemens_club",
    // "thompson_and_bleecker",
    // "haleyhenry",
    // "amber_lantern_brewing_company",
    // "kings_county_brewers_collective",
    // "the_sole_proprietor",
    // "blue_note_jazz_club",
    // "roxys_arcade",
    // "interlude_rooftop_lounge",
    // "the_pig__parrot",
    // "down_the_hatch",
    // "ithaca_farmers_market_pavilions",
    // "carraghers",
    // "the_coyote_club",
    // "parkside_rotisserie__bar",
    // "talking_cursive_brewing_company",
    // "the_richmond_by_mortalis_brewing",
    // "burp_castle",
    // "cubbyhole_bar",
    // "lionheart_pub_and_brewery",
    // "the_stumble_inn",
    // "the_keep",
    // "fairport_music_and_arts_festival",
    // "blue_midtown",
    // "sportsmens_tavern",
    // "yes_apothecary",
    // "el_jefe_taco_bar",
    // "krasi",
    // "terroir",
    // "sons_of_essex",
    // "city_vineyard",
    // "coltivare",
    // "the_hangar_on_the_hudson",
    // "crisp_rochester",
    // "puffys_tavern",
    // "bk_backyard_bar",
    // "circe_restaurant__bar",
    // "wicked_wolf_hoboken",
    // "roxannes",
    // "albany_symphony_orchestra",
    // "the_9s",
    // "fresh_kills_bar",
    // "berlin",
    // "bounce_sporting_club",
    // "the_skinny",
    // "the_palladium_nightclub",
    // "pdt",
    // "the_lilypad",
    // "basketball_hall_of_fame",
    // "the_music_box_at_borgata_hotel_casino__spa",
    // "gypsy_parlor",
    // "wildcard_bar",
    // "flour_city_station",
    // "mercury_lounge",
    // "mulrooneys",
    // "albany_riverfront_jazz_festival",
    // "rumba_lounge",
    // "schimanski",
    // "the_rhine_house",
    // "boch_center_wang_theatre",
    // "ships_pub",
    // "the_upstairs",
    // "soho_grand_hotel",
    // "the_met_caf",
    // "11th_street_bar",
    // "off_the_rails",
    // "temple_bar__grille",
    // "kitty_hoynes_irish_pub",
    // "the_rum_house",
    // "icon__venu_nightclub",
    // "midnights",
    // "platforms_dance_club",
    // "the_mercantile",
    // "trata",
    // "brandy_library",
    // "ocallaghans_pub",
    // "the_hops_spot",
    // "los_mariscos",
    // "the_pool_after_dark",
    // "thatcher_st_pub",
    // "sofia_wine_bar__caf",
    // "the_downstairs",
    // "legal_sea_foods__kendall_square",
    // "venu",
    // "troost",
    // "yvonnes",
    // "sogno_toscano_market__wine",
    // "priya_indian_cuisine",
    // "moonshine_alley",
    // "moonstones",
    // "pauls_cocktail_lounge",
    // "rumpus_room",
    // "scarpetta",
    // "theater_for_the_new_city",
    // "killarney_rose",
    // "troy_savings_bank_music_hall",
    // "empire_underground",
    // "winnies_jazz_bar",
    // "barcade",
    // "nowhere_special_libations_parlor",
    // "bosco",
    // "shinjis",
    // "the_flatiron_room__nomad",
    // "katana_kitten",
    // "hudson_table",
    // "the_gate_house",
    // "niagara",
    // "thyme_bar",
    // "the_perfect_pint",
    // "argos_inn",
    // "emerson_colonial_theatre",
    // "the_lava_clubangry_garlicthe_yorkwildflowers",
    // "guilt",
    // "the_daily_refresher",
    // "von",
    // "storyville_nightclub",
    // "underdog",
    // "abilene_bar_and_lounge",
    // "orbis_lounge",
    // "kiss_kiss_nightclub",
    // "la_cava",
    // "the_fox_and_the_burn_at_river_street_market",
    // "bully_boy_distillers",
    // "doha_bar__lounge",
    // "faegans_cafe__pub",
    // "the_belfry",
    // "albany_civic_theater",
    // "mix_kitchen__bar",
    // "schooners_riverside_pub",
    // "hutaoli_music_restaurant__bar",
    // "the_mad_monkfish",
    // "coppelia",
    // "slate_ny",
    // "carrie_nation_cocktail_club",
    // "gramercy_theatre",
    // "up_stairs",
    // "cinemapolis",
    // "swan_dive",
    // "oconnors_restaurant__bar",
    // "the_salon",
    // "skylark_lounge",
    // "the_angry_goat_pub",
    // "oslatterys_irish_restaurant__pub",
    // "tong",
    // "salt_city_bar",
    // "ale_n_angus_pub",
    // "wildflowers",
    // "albany_center_gallery",
    // "the_knickerbocker",
    // "blue_cross_arena",
    // "storyville",
    // "club_macanudo",
    // "sour_mouse",
    // "alibi_bar_and_lounge",
    // "big_bar",
    // "whiskeys_on_the_water",
    // "the_ravens_club",
    // "oduffys_pub",
    // "broadstone_bar__kitchen",
    // "magic_bag_theatre",
    // "bar_primi_penn_district",
    // "mercury_burger_bar",
    // "swan_room",
    // "ethyls_alcohol_and_food",
    // "foxy_johns_bar__kitchen",
    // "the_morrie",
    // "the_thirsty_hound",
    // "hudsons_classic_grill",
    // "hopcat_east_lansing",
    // "creston_brewery",
    // "eaglemonk_pub_and_brewery",
    // "bartusi",
    // "crunchys",
    // "smalls_bar",
    // "the_malt_house",
    // "cask__co",
    // "charlies_bar__grille",
    // "levante",
    // "redcoat_tavern",
    // "9th_avenue_saloon",
    // "vangos_pizza__cocktail_lounge",
    // "brick_and_porter",
    // "baby_brasa",
    // "club_54",
    // "1803_nyc",
    // "red_cedar_spirits",
    // "black_tap",
    // "the_sugar_house",
    // "mcsorleys_old_ale_house",
    // "atwater_brewery",
    // "bushwick_public_house",
    // "death__co",
    // "frederik_meijer_gardens__sculpture_park",
    // "beggars_banquet_restaurant_and_saloon",
    // "overstory",
    // "university_roadhouse",
    // "rockys",
    // "the_morrie__royal_oak",
    // "rumors_night_club",
    // "lilys_seafood",
    // "the_sovengard",
    // "black_pearl_ann_arbor",
    // "six_lounge",
    // "the_dickens",
    // "latitude_42_brewing_company",
    // "scl_royal_oak",
    // "stone_street_tavern",
    // "bierkeller",
    // "long_road_distillers",
    // "blinkys_bar",
    // "cherry_on_top",
    // "ore_dock_brewing_company",
    // "westlight",
    // "the_crown",
    // "pubkey",
    // "the_woo_woo",
    // "offworld_arcade",
    // "raouls_restaurant",
    // "mad_tropical",
    // "mr_fongs",
    // "yours_sincerely",
    // "dublin_square",
    // "the_whitney",
    // "mareluna",
    // "bar_nine",
    // "boogie_fever_night_club",
    // "the_friesian_gastro_pub",
    // "lockharts_bbq",
    // "rudys",
    // "royal_oak_brewery",
    // "the_beast_next_door",
    // "new_holland_brewing_co__grand_rapids_brewpub_the_knickerbocker",
    // "pronto_restaurant__video_bar",
    // "birch_lodge",
    // "zingermans_roadhouse",
    // "reception_bar",
    // "the_red_lion",
    // "oak_cafe",
    // "exodos_rooftop",
    // "liquid_note",
    // "elektricity_nightclub",
    // "parkside_lounge",
    // "heidelberg",
    // "night_of_joy",
    // "rooftop_93",
    // "hardings",
    // "orchid_ferndale",
    // "employees_only",
    // "bar_b",
    // "blind_pig",
    // "the_ear_inn",
    // "whiskey_tavern",
    // "lou_and_harrys_sports_bar",
    // "rp_mcmurphys",
    // "brickyard_craft_kitchen_and_bar",
    // "the_up__up",
    // "the_bob",
    // "le_poisson_rouge_lpr",
    // "valerie",
    // "swing_46",
    // "wan_wan",
    // "park_avenue_armory",
    // "tavern_on_reade",
    // "patent_pending",
    // "crystal_lake_brooklyn",
    // "fifth_avenue",
    // "st_mazie_bar__supper_club",
    // "rabbit_hole",
    // "grand_woods_lounge",
    // "mollusca",
    // "time_will_tell",
    // "temple_bar",
    // "the_brown_jug",
    // "the_hunterian_bar",
    // "3fifty_terrace",
    // "the_blue_leprechaun",
    // "smugglers_run",
    // "the_back_room",
    // "arturos_restaurant",
    // "city_built_brewing_company",
    // "daxton_hotel",
    // "alphaville",
    // "saugatuck_brewing_company",
    // "ale_marys_beer_hall",
    // "new_dodge_lounge",
    // "the_flying_cock",
    // "trinity_place",
    // "sol_blu_lounge__taproom",
    // "bootleg_bar",
    // "toms_oyster_bar",
    // "saint_andrews_hall",
    // "the_robin_theatre",
    // "louies_trophy_house",
    // "billys_lounge",
    // "blue_llama_jazz_club",
    // "white_horse_tavern",
    // "devos_performance_hall",
    // "the_ivory_peacock",
    // "russian_vodka_room",
    // "library_kitchen__tap_house",
    // "gossip_bar_nyc",
    // "keybar",
    // "the_infamous",
    // "simons_after_dark",
    // "michigan_lottery_amphitheatre_at_freedom_hill",
    // "wild_bull",
    // "boxers_chelsea",
    // "the_mitten_brewing_company",
    // "damatos",
    // "goodnite_gracie",
    // "botanica_bar",
    // "the_painted_lady",
    // "pauls_casablanca",
    // "the_craic",
    // "ann_arbor_distilling_company",
    // "heavy_woods",
    // "mesa_tacos_and_tequila",
    // "polka_dot",
    // "le_suprme",
    // "harrys_detroit_bar__grill",
    // "otooles",
    // "the_tin_can",
    // "storehouse",
    // "the_film_lab",
    // "the_campbell",
    // "smalls_bar",
    // "shift",
    // "ways__means",
    // "the_bob",
    // "the_intersection",
    // "skinny_dennis",
    // "speakez_lounge",
    // "the_dead_rabbit",
    // "founders_brewing_co",
    // "radegast_hall_and_biergarten",
    // "cafe_carlyle",
    // "johnnys",
    // "nightcap",
    // "the_wayland",
    // "northern_lights_lounge",
    // "quigleys_irish_pub",
    // "chicago_prime_steakhouse",
    // "bayou_bowl",
    // "scandals",
    // "prairie_moon",
    // "principle_food__drink",
    // "fatty_arbuckles_pub",
    // "chimes_restaurant",
    // "fat_boyz_neighborhood_bar",
    // "shaw_center_for_the_arts",
    // "enochs_irish_pub__cafe",
    // "studio_59_lounge",
    // "the_vintage",
    // "davenports_piano_bar_and_cabaret",
    // "heaven_can_wait",
    // "thrive_event_hall",
    // "roak_brewing_co_tap_room",
    // "the_vierling",
    // "hayride_scandal",
    // "tv_lounge",
    // "pinball_petes",
    // "shakespeares_pub",
    // "cricketts_legacy_sports_bar",
    // "strange_brew",
    // "mt_barrels",
    // "comedy_showcase",
    // "freds",
    // "meze_mediterraneo",
    // "duvics",
    // "the_bulldog",
    // "l_bar_at_lauberge",
    // "mchenry_county_fair_association_fairgrounds",
    // "lemon",
    // "fifth_avenue_billiards",
    // "red_goose_saloon",
    // "carroll_place_nyc",
    // "the_greenroom",
    // "bald_eagle_pub",
    // "vermilionville",
    // "the_crossing",
    // "the_foxtail_on_the_lake",
    // "steinhaus",
    // "city_park",
    // "clicks_billiards__sports_bar_baton_rouge",
    // "the_score_gr",
    // "the_rox_bar",
    // "double_door",
    // "event_center_kenner",
    // "white_tavern",
    // "the_market_restaurant",
    // "bayou_smoke_monroe_cigar_lounge",
    // "whirlyball",
    // "jolie_pearl_oyster_bar",
    // "bears",
    // "varsity_theatre__baton_rouge_la",
    // "donkey_taqueria",
    // "byron_cigar_lounge",
    // "circa_21_dinner_playhouse",
    // "big_mikes_bbq_smokehouse",
    // "grand_dads_bar",
    // "fieldhouse",
    // "supergeil",
    // "arpeggios_lounge__event_center",
    // "shreveport_municipal_auditorium",
    // "whiskeys_on_the_water",
    // "the_maple_leaf_bar",
    // "cliff_bells",
    // "sixtyfour__wine_bar__kitchen",
    // "chandlers_chophouse_grille",
    // "pyramid_scheme",
    // "meanwhile_bar",
    // "house_o_soul",
    // "anthonys_sports_bar__grill",
    // "up_north_ale_house",
    // "wealthy_theatre",
    // "mood_ring",
    // "superiors_steakhouse",
    // "harpers_restaurant__brewpub",
    // "bourbon_pub__parade",
    // "liquid_blues_ltd",
    // "the_house_in_tigerland",
    // "flying_tiger_brewery",
    // "webers",
    // "bumbos_bar",
    // "riverbeat_festival",
    // "hotel_arista",
    // "red_white_and_brew",
    // "the_ice_bar__golden_nugget",
    // "bisou_lounge",
    // "oasis_hookah_lounge",
    // "bottoms_up_sports_bar__grill",
    // "daiquiris__company",
    // "the_stache",
    // "ward_eight",
    // "tipitinas",
    // "oz_nightclub",
    // "adopted_dog_brewing",
    // "raccoon_motel",
    // "frankies_blue_room",
    // "buddy_guys_legends",
    // "stonewood_ale_house",
    // "the_stage",
    // "our_moms_restaurant_and_bar",
    // "the_delft_bistro",
    // "transpecos",
    // "the_native",
    // "bounce",
    // "the_waterfront_wyandotte",
    // "whiskey__vine",
    // "bills_bar__burger__golden_nugget",
    // "twonine",
    // "the_library_riot",
    // "blue_moon_saloon",
    // "marble_bar",
    // "220_merrill",
    // "zydeco",
    // "spartan_ale_house",
    // "soundbar",
    // "bakers_keyboard_lounge",
    // "kahala_koa",
    // "one_well_brewing",
    // "00_bar__nightclub__lounge",
    // "era_social_club",
    // "bat_17",
    // "red_maple",
    // "rock_n_bowl_new_orleans",
    // "magdaleno_ristorante_wine_bar",
    // "chenery_auditorium",
    // "slims_ykiki",
    // "the_metropolitan",
    // "crying_eagle_brewing",
    // "park_place",
    // "walkons_sports_bistreaux",
    // "harveys_on_the_mall",
    // "texas_de_brazil",
    // "bodega_wine_dive",
    // "ballys_shreveport_casino__hotel",
    // "dorians",
    // "stellas_lounge",
    // "526_main",
    // "schaumburg_public_house",
    // "tgif_dance_party",
    // "connies_hide_away",
    // "henry_turner_jrs_listening_room_heritage_museum",
    // "the_cabin",
    // "noon_whistle_brewing",
    // "georges_place",
    // "empire_burge",
    // "the_chicago_theater",
    // "commanders_palace",
    // "rozz_tox",
    // "windrush_grill",
    // "oyster_bar__grille",
    // "peggy_kinnanes_irish_restaurant__pub_in_arlington_heights",
    // "alchemi",
    // "peanut_barrel",
    // "westwood_tavern",
    // "nite_town",
    // "the_tap_room",
    // "1913_restaurant__wine_bar",
    // "oak_city_grille",
    // "the_spotted_cat_music_club",
    // "necto_nightclub",
    // "fieldhouse_bar__grill",
    // "the_stamped_robin",
    // "crosstown_arts_green_room",
    // "jovonnes_lounge",
    // "the_winchester",
    // "fumblebrewski",
    // "flying_heart_brewing__pub",
    // "rikenjaks",
    // "the_outing_club",
    // "the_texas_club",
    // "live",
    // "delilahs",
    // "jam_productions",
    // "tony_mandinas",
    // "pizza_artista",
    // "bells_eccentric_cafe",
    // "eastown_hookah_lounge",
    // "jackson_ave_pub",
    // "shenannigans",
    // "st_cecilia_music_center",
    // "harmony_brewing_company",
    // "norms_daiquiris",
    // "hazels",
    // "the_brass_monkey",
    // "the_panorama_music_house",
    // "the_lucky_monk",
    // "elbo_room",
    // "emerson_and_oliver",
    // "brunos_tavern",
    // "winestock",
    // "luna_live",
    // "ricks_american_cafe",
    // "copper_vine",
    // "club_sugas",
    // "tejas_kitchen",
    // "olde_tyme_grocery",
    // "the_holiday_bar",
    // "shirleys_piano_bar",
    // "raising_canes_river_center",
    // "kumas_corner",
    // "the_riviera_theatre",
    // "grand_bayou_noir",
    // "daiquiri_express",
    // "sleeping_village",
    // "mash",
    // "willis_show_bar",
    // "rock_n_bowl_de_lafayette",
    // "cuban_creations_cigar_bar",
    // "one_twenty_live",
    // "the_maison",
    // "the_freetown_boom_boom_room",
    // "the_carousel_bar",
    // "lauberge_casino_resort",
    // "the_vic",
    // "peppers_pizzeria",
    // "space",
    // "trapps",
    // "the_mitten_brewing_co",
    // "republic",
    // "hey_nonny_in_arlington_heights",
    // "the_necto_night_club",
    // "chelseas_live",
    // "hotel_blackhawk",
    // "main_st_pub",
    // "real_time_sports",
    // "the_lantern",
    // "presidential_palace",
    // "stairway_royal_oak",
    // "wintrust_field",
    // "poor_boy_lloyds",
    // "daiquiri_station",
    // "temperance_beer_co",
    // "stuckos_pub__grill",
    // "good_night_john_boy",
    // "bayou_teche_brewery",
    // "hurricane_alley_live",
    // "frozen_pirogue",
    // "fulton_alley",
    // "pronto",
    // "pegasus_night_club",
    // "nichols_concert_hall",
    // "old_absinthe_house",
    // "cafe_amelie",
    // "bottoms_up_on_7th",
    // "texas_club",
    // "lafittes_blacksmith_shop_bar",
    // "finn_mccools_irish_pub",
    // "the_ghostbar",
    // "herbyks",
    // "the_noble_savage_tavern",
    // "rezervoir_lounge",
    // "post_42",
    // "josh_lounge",
    // "chicago_prime_italian",
    // "the_northcott_liquorette",
    // "millers_ale_house",
    // "cowboys",
    // "fritzels_european_jazz_club",
    // "babs_underground",
    // "the_matrix_room_and_megs_lounge",
    // "parish_restaurant__bar",
    // "the_office_bar",
    // "h2o_pool__bar",
    // "hollywood_palms_a_cinema_bar__eatery",
    // "ellendale_country_club",
    // "the_hang_uppe",
    // "the_rust_belt",
    // "pinstripes",
    // "social_kitchen__bar",
    // "houmas_house",
    // "reggies_chicago",
    // "constellation",
    // "refuge_worldwide",
    // "gendusas_italian_market",
    // "iron_bay_restaurant__drinkery",
    // "city_works",
    // "mulligans_pub",
    // "detroit_street_filling_station",
    // "churchills_bistro",
    // "urban_vines_winery__brewery",
    // "rinse_france",
    // "two_way_inn",
    // "garage_bar__grill",
    // "rendezvous",
    // "chips_daiquiris",
    // "the_black_salt",
    // "the_yard_goat",
    // "crystal_events",
    // "stage_left",
    // "tequila_blue",
    // "columbia_street_rock_n_blue_cafe",
    // "machine_engineered_dining__drink",
    // "morettis_ristorantepizzeria",
    // "lotus_club",
    // "bleu_detroit",
    // "westwood_tavern_and_tap",
    // "bolt_nightclub",
    // "timeless_moments_banquet",
    // "studio5",
    // "beerhead_bar__eatery",
    // "iron_gate_bar",
    // "dwights",
    // "meson_sabika",
    // "red_dragon_listening_room",
    // "windy_city_dueling_pianos",
    // "shananigans",
    // "the_meanwhile_bar",
    // "tailgators_bar",
    // "jungle_casino",
    // "midtown_gr",
    // "cuvee_wine_bar_and_bistro",
    // "courtyard_grand_rapids_downtown",
    // "polonia_restaurant",
    // "evenflow_music__spirits",
    // "the_green_door_blues_bar__grill",
    // "golden_nugget_lake_charles_hotel__casino",
    // "gator_jakes_bar__grill",
    // "enchanted_forest_music_hall",
    // "big_country",
    // "olive_or_twist",
    // "sofies_whiskey__wine",
    // "bon_temps_bar__grill",
    // "ninety9_bistro__bar",
    // "roux__brew_seafood_and_steakhouse",
    // "tallulah_wine_bar",
    // "phoenix",
    // "metro",
    // "the_studio_at_414",
    // "saturn_bar",
    // "foundation_room",
    // "evanston_pour",
    // "green_door_distilling_co",
    // "teddys_juke_joint",
    // "celeste",
    // "vlounge",
    // "the_rock_on_3rd",
    // "main_line",
    // "the_lodge_tavern",
    // "smartbar",
    // "whiskey_hill_brewing__pizza_bar",
    // "mother_hubbards_sports_pub",
    // "fritzys_tavern",
    // "kavanaughs_hilltop",
    // "carols_pub",
    // "spybar_chicago",
    // "martyrs",
    // "seven_nightclub",
    // "five_and_dime",
    // "the_officethe_aviary",
    // "the_bassment",
    // "offsides_sports_bar_and_grill",
    // "roosters_sports_bar_and_grill",
    // "rock_island_ale_house",
    // "woodstock_opera_house",
    // "vander_veer_park",
    // "streeters_tavern",
    // "up_skybar",
    // "gman_tavern",
    // "ortmanns_red_iron_tavern",
    // "rhythm_city_casino",
    // "vibrant_arena_at_the_mark",
    // "la_malquerida_nightclub",
    // "the_violet_hour",
    // "estelles",
    // "hideout_inn",
    // "stoney_creek__moline",
    // "rascals_live",
    // "chicago_symphony_orchestra",
    // "radicle_effect_brewerks",
    // "quarter_til_tap",
    // "nicks_beer_garden",
    // "concord_music_hall",
    // "double_clutch_brewing_co",
    // "good_to_go_jamaican_cuisine",
    // "pickstaiger_concert_hall",
    // "analog_arcade_bar",
    // "old_town_ale_house",
    // "the_garage_bar__sandwiches",
    // "115_bourbon_street",
    // "tini_on_the_ave",
    // "linden_grill",
    // "duffys_place",
    // "r_bar",
    // "potawatomi_park",
    // "vegetable_buddies",
    // "howl_at_the_moon",
    // "club_soda",
    // "bent_river_brewing",
    // "rohrs",
    // "spirited",
    // "be_here_now",
    // "mcginnis_pub",
    // "franklin_house",
    // "schubas_tavern",
    // "terrace_room",
    // "orourkes_public_house",
    // "evil_czech_brewery_and_public_house",
    // "farm_stand_second_story_cocktail_lounge",
    // "m_moggers_restaurant__pub",
    // "hotel_tango_artisan_distillery",
    // "spot_tavern",
    // "trion_tavern",
    // "don_quijote",
    // "the_mousetrap",
    // "the_dashin",
    // "the_hoppy_gnome",
    // "the_indiana_whiskey_company",
    // "prized_pig_bbq",
    // "galley_sports_pub",
    // "madison_oyster_bar",
    // "rocky_river_tap_and_table",
    // "power_plant_bar_and_grill",
    // "four_stop_bar",
    // "corbys_irish_pub",
    // "1925_pubhouse",
    // "brothers_bar__grill_south_bend",
    // "shoreline_brewery",
    // "klepz_resturaunt",
    // "the_mansion_at_pete_dye",
    // "thunderbird",
    // "the_wine_gallery_at_villa_macri",
    // "poplar_pub",
    // "hacienda_mexican_restaurant",
    // "valley_sports_bar",
    // "joes_grille",
    // "on_the_roxx",
    // "hoosier_dome",
    // "lasalle_kitchen__tavern",
    // "doc_pierces_restaurant",
    // "westwind_brewery",
    // "zorn_brew_works_co",
    // "black_dog_pub__restaurant",
    // "bier_brewery__tap_room",
    // "northside_tap",
    // "memorial_opera_house",
    // "the_bend_pub_and_grill_at_the_ramada_south_bend",
    // "corndance_tavern",
    // "fuse_bar__nightclub",
    // "bohannons_east",
    // "ruoff_music_center",
    // "the_clubhouse",
    // "event_center",
    // "pieres_entertainment_center",
    // "valpo_pour_house",
    // "zim_marss",
    // "villa_macri_ristorante",
    // "monterrey_mexican_bar__gril",
    // "egyptian_room_at_old_national_centre",
    // "the_brass_rail",
    // "taylors_pub__grill_at_greenbriar",
    // "sonka_irish_pub",
    // "the_garage_arcade_bar",
    // "the_meeting_grounds",
    // "navarre_hospitality_center",
    // "rock_the_ruins",
    // "the_red_room",
    // "the_lerner_theater",
    // "le_nocturne",
    // "radio_radio",
    // "the_porter_health_amphitheater",
    // "the_jazz_kitchen",
    // "hop_station",
    // "twin_archer_brewpub",
    // "clifton_ballroom",
    // "lincoln_flush",
    // "parea_restaurant__lounge",
    // "the_guardian_brewing_company",
    // "mateys_restaurant",
    // "3up_rooftop_lounge",
    // "savages_ale_house",
    // "the_cellar_wine_bar",
    // "splitz_sports_bar",
    // "dupont_grille",
    // "the_lauber",
    // "lafayette_theater",
    // "the_jazz_club",
    // "grouse_room",
    // "charlies_pub__grub",
    // "uptown_kitchen",
    // "sandcut_tavern",
    // "8_seconds_saloon",
    // "union_50",
    // "the_patron_saint_indy",
    // "the_hideaway_at_the_lasalle",
    // "windsor_ballroom",
    // "baker_street",
    // "the_rathskeller",
    // "fiddlers_hearth",
    // "the_exchange_bar",
    // "bar_botics",
    // "deer_park_irish_pub",
    // "four_winds_field",
    // "baker_street_steakhouse",
    // "bar_louie_granger",
    // "sugar_creek_vineyard_and_winery",
    // "stacks_bar__grill",
    // "french_lick_springs_hotel_lobby",
    // "catch_table__tap",
    // "midway_tavern",
    // "big_league_sports_bar_and_grill",
    // "hifi_annex",
    // "union_pool",
    // "schottenstein_center",
    // "wolstein_center",
    // "the_agora",
    // "bradley_symphony_center",
    // "astra_kulturhaus_berlin",
    // "hobart_art_theatre",
    // "the_view_tavern",
    // "bmo_pavilion",
    // "bop_stop",
    // "linnemans_riverwest_inn",
    // "simeris_old_town_tap",
    // "yorckschlsschen",
    // "quasimodo",
    // "hifi_indy__hifi_annex",
    // "kate_oconnors_irish_pub",
    // "wild_at_heart",
    // "miller_high_life_theatre",
    // "ace_of_cups",
    // "old_national_center",
    // "lido",
    // "atrane",
    // "lost_and_found",
    // "gibraltar_mke",
    // "goblin__the_grocer",
    // "jacobs_pavilion",
    // "forest_city_brewery",
    // "chill_on_the_hill",
    // "hangovereasy",
    // "so36",
    // "dayton_metro_library",
    // "burn_em_brewing",
    // "dockside_nightclub",
    // "embassy_theatre",
    // "metro_nightclub_and_restaurant",
    // "primary_chicago",
    // "pikks_tavern",
    // "the_mill_terre_haute",
    // "palais_royale",
    // "clowes_memorial_hall",
    // "oasis_bar__grill",
    // "speakeasy_at_the_spa",
    // "the_clubhouse_muncie",
    // "elm_street_brewing_co",
    // "the_verve",
    // "blind_pig_tavern__grill",
    // "stereo_nightclub",
    // "amazing_joes_grill",
    // "clyde_theatre",
    // "big_shots_pub",
    // "chevvys_pizza__sports_bar",
    // "deluxe_at_old_national_centre",
    // "brothers_bar_and_grill",
    // "sidebar_south_bend",
    // "tree_house_eatery_drinkery",
    // "morris_performing_arts_center",
    // "the_chug",
    // "foellinger_theater",
    // "slippery_noodle_inn",
    // "the_exchange",
    // "linebacker_lounge",
    // "sweetwater_performance_pavilion",
    // "elliot_hall",
    // "diloreto_club",
    // "the_georgia_theatre",
    // "morton_theatre",
    // "mideast_club",
    // "morton_theatre",
    // "moondogs",
    // "mjq_concourse",
    // "red_light_cafe",
    // "harlows",
    // "the_regent_theater",
    // "the_smell",
    // "the_moroccan_lounge",
    // "the_mint",
    // "vibrato_grill_jazz",
    // "the_peppermint_club",
    // "top_cats",
    // "madison_theater",
    // "the_wolfhound",
    // "village_vanguard",
    // "terraza_7",
    // "national_sawdust",
    // "elsewhere",
    // "bargemusic",
    // "nostalgia",
    // "washington_house",
    // "sellersville_theater",
    // "franklin_music_hall",
    // "newtown_theatre",
    // "underground_arts",
    // "noto_philadelphia",
    // "chris_jazz_cafe",
    // "concourse",
    // "the_fallser_club",
    // "the_queen",
    // "the_grand_opera_house",
    // "keswick_theatre",
    // "voodoo_brewery__state_college",
    // "zenos",
    // "18th_street_lounge",
    // "ronnie_scotts_jazz_club",
    // "the_vanguard",
    // "yoshis_san_francisco",
    // "roseland_theater",
    // "neumos",
    // "the_triple_door",
    // "the_southgate_house_revival",
    // "the_saxon_pub",
    // "mayfair_austin",
    // "cervantes_masterpiece_ballroom",
    // "lost_lake_lounge",
    // "jamboree",
    // "south_side_ballroom",
    // "trees_dallas",
    // "the_factory_in_deep_ellum",
    // "house_of_blues_dallas",
    // "flash",
    // "union_stage",
    // "hopscotch_coffee__records",
    // "jamminjava",
    // "baltimore_soundstage",
    // "friends_and_lovers",
    // "the_independent",
    // "thunderbird_caf__music_hall",
    // "prysm_nightclub",
    // "gallery5arts",
    // "brambly_park",
    // "930_club",
    // "the_pocket",
    // "dc9_nightclub",
    // "madamsorgan",
    "blackcat",
    "tallyhotheater",
    "buckhead_saloon",
    "the_masquerade",
    "miami_beach_bandshell",
    "third_door",
    "the_hippodrome_theater",
    "the_basement_nashville",
    "mr_smalls_theatre",
    "curitiba_art_cafe",
    "thecamel",
    "the_anthem",
    "the_blue_note_grill",
    "hofrva",
    // "hyatt_place_portlandold_port",         // hyatt hotel
    // "woolsey_hall",                     // yale uni
    // "corinth_free_methodist_church",         // church
    // "the_asbury",                         // hotel website
    // "liberty_science_center",            // science center
    // "the_garrison",                    // breaks everything
    // "asbury_park_boardwalk",           // website is a no
    // "convention_hall",             // wtf is this website
    // "captain_toms_tiki_bar",                    // no website
    // "shepard_park",              // county website
    // "hard_rock_live_at_etess_arena",            //hardrock website
    // "the_grand_at_golden_nugget",             // casino
    // "luthiers_coop", // infinite calendar
    // "ivan_kanes_royal_jelly_burlesque_nightclub",      // no website
    // "tropicana_showroom", // infinite calendar
    // "caesars_atlantic_city_hotel__casino",         // caesars
    // "elley_long_music_center",         // this website if for a youth center
    // "the_state_house",        // no websit
    // "first_united_methodist_church_of_lake_george",     // this is a church
    // "saratoga_performing_arts_center_spac",            // no website
    // "nikki_tiger",             // no website
    // "heirloom",               // no website
    // "the_misfit",               // MULTIPLE VENUES
    // "the_porthole",            // infinite calendar?
    // "armsby_abbey", // infinite calendar?
    // "gaslight",         // facebook is the website
    // "saratoga_casino_hotel",            // hotel casino
    // "tang_teaching_museum",           // edu website
    // "water_tower_bar",        // arlo hotel
    // "folklife_center",             // library
    // "center_for_remembering__sharing",         // weird website
    // "cuba_libre_restaurant__rum_bar",          // multiple locations
    // "albany_institute_of_history__art",        // albany institute
    // "trifecta",           // fourseasons hotel
    // "nublu",            // no idea what this website is... multiple venues
    // "lizard_lounge",                   // poorly made wordpress website, infinite dates
    // "albany_performing_arts_center",          // k12 aircraft carrier
    // "brick__mortar",           // no website
    // "high_line",               // standard hotels website
    // "phd_rooftop_lounge",             // taogroup venue
    // "darien_lake_amphitheater",           // niarga website
    // "carousel",              // weird events website
    // "berklee_performance_center",              // berklee
    // "mels",              // taogroup venue group
    // "community_school_of_music_and_arts",          // college website
    // "ithaca_tompkins_regional_airport",        // what is this website
    // "mountain_bar",        // caesars
    // "eastman_theatre",                 // edu website
    // "the_java_room",         // google.com as website domain
    // "symphony_hall",              // multiple venues
    // "ithaca_college_dillingham_center",          // ithaca college website
    // "upright_citizens_brigade_theatre",       // comedy page wiht multiple venues
    // "the_claridge_hotel",           // website doesn't work
    // "lupos_heartbreak_hotel",           // hotel website
    // "nurse_bettie", // infinite calendar
    // "britesmith_brewing",         // infinite pagination
    // "alive_at_five",         // albany events website
    // "birdys",          // yelp website
    // "celon_bar_and_lounge",          // hotel website
    // "kraine_theater",          // recursive url slug :(
    // "market_hotel", // hotel website
    // "the_muddy_charles_pub",           // mit website
    // "gypsybar",         // mgmt website
    // "ithaca_marriott_downtown_on_the_commons", // marriott website
    // "buffalo_river_works",     // infinite calendar
    // "rubin_museum_of_art",    // museum website
    // "massry_center_for_the_arts",    //university website
    // "water_tower",              // arlo hotel website
    // "the_lark_street_tavern",     // one of the real bad apples & maybe a sitemap issue?
    // "electric_room",        // hotel website
    // "duffs_brooklyn", // super slow website
    // "the_woo_bar__grill", // one of those that just doesn't work at all'
    // "92nd_street_y",     // /tickets isn't for events so you get a lot of spam'
    // "drifters", // no website
    // "cafe_939", // berkeley is the website
    // "moma_museum_of_modern_art", // art museum website
    // "cornell_university_bailey_hall", // university website
    // "cornell_university_bailey_hall", // university website
    // "bowery_ballroom",     // already have this venue
    // "ocean_casino_resort", // weird vibes coming from this website
    // "elysian_cafe",           // goes forever
    // "rochester_museum__science_center", // science center
    // "theatre_80_saint_marks", // infinite calendar
    // "mgm_springfield",  // MGM
    // "wilbur_theatre", // infinite calendar
    // "albany_public_library", // public library
    // "providence_childrens_museum",   // museum website
    // "the_brattle_theatre", //infinite calendar problem
    // "bryant_park",      // park website
    // "hard_rock_cafe_atlantic_city", // hard rock website
    // "la_mama_etc",     // weird website
    // "nbt_bank_stadium", // county park stadium
    // "brick__mortar_music_hall", // recursive URL problem
    // "lincoln_hall",              // multiple venues
    // "nazareth_college_arts_center",  // college website
    // "harbor_rooftop_club",          // website too general
    // "arcadia_creek_festival_place",  // park website
    // "skydeck",   // multiple venues
    // "j_gardellas_tavern",       // infinite menu
    // "gusoline_alley", // myspace.com is the website lol
    // "hudson_river_park", // website is for a park
    // "the_brown_door", // citysearch.com is the website?
    // "tip_top_deluxe_bar__grill",         // wtf is ticketweb.com?
    // "graduate_rock_bar",           // hotel website
    // "roger_b_chaffee_planetarium",  // museum website
    // "specialeventsolyentcom",       // 313presents has multiple venues
    // "the_blond",                    // 11 howard website
    // "hotel_vegas",                   // website URL is broken
    // "excellence_event_center",       // goes on forever
    // "nells_airport_lounge",            chamber of commerce website???
    // "courtyard_by_marriott_new_orleans_westbankgretna", marriott
    // "doubletree_by_hilton",          // hilton hotel website
    // "preservation_hall", // calendar goes on forever
    // "holiday_inn_new_orleans_west_bank_tower", // hotel website
    // "the_great_room_lounge_at_the_chicago_marriott", // marriott website
    // "smash_bash_festival",       // wonderville is the venue
    // "caddyshack_icehouse",       // just breaks things
    // "horseshoe_lake_charles",    // caesars.com???
    // "rosas_lounge",              // calendar goes on forever
    // "grant_street_dancehall",      // explore lousiana website?
    // "off_square_music",           // goes on for a long time
    // "boopalus",                   // yelp as the website
    // "ufo_factory",                 // linktree is the website
    // "the_ark",                   // multiple venues
    // "sams_place",                // what is this website???
    // "northwestern_universitys_bienen_school_of_music", // northwester website
    // "renaissance_schaumburg_convention_center_hotel", // marriot hotels as website
    // "obs_bar_and_grill",                   // facebook is website
    // "scallys_roadside",                    // facebook is website
    // "charming_event_center",                // yelp is the website
    // "puth_family_theater",              // multiple venues and goes forever
    // "the_korner_lounge",                   // yelp if the website lol
    // "lucky_bernies_woodstock",         // problematic - goes forever
    // "tao_bistro_and_nightclub",       // multiple venues
    // "the_green_mill",              // problematic - goes forever
    // "foellingerfreimann_botanical_conservatory", // i don't think there are music events?j
    // "the_vogue_theatre",   // multiple venues
    // "hendershots",               // needs client-side rendering
    // "the_hifi",                    // problematic - blocks us?
    // "woodward_theater",             // problematic
    // "taft_theatre",                 // problematic - infinite calendar
    // "venkmans",                 // problematic
    // "terminal_west",            // needs client-side rendering
    // "3_dots_downtown",                // problematic - calendar goes forever
    // "dna_lounge",            // pain in the ass
    // "the_vogue",                    // problematic - times out a lot + multiple threaters
    // "thebroadberry"            // problematic - blocks us and has multple venues listed
    // "jay_pritzker_pavilion",      // problematic - literally just breaks things
    // "kingston_mines",             // problematic - literally just breaks things
    // "mojos_sports_bar",              /// literally just breaks
    // "feed__seed_lafayette",         // literally just breaks things
  ];

  return initVenueUsernames;
}

export async function getUserById(userId: string): Promise<UserModel | null> {
  const userSnap = await usersRef.doc(userId).get();

  if (!userSnap.exists) {
    return null;
  }

  const user = userSnap.data() as UserModel;
  return user;
}

export async function getUserByUsername(username: string) {
  const userSnap = await usersRef.where("username", "==", username).get();

  if (userSnap.docs.length === 0) {
    // console.error(`[!!!] no user found for username`);
    return null;
  }

  const user = userSnap.docs[0].data() as UserModel;
  return user;
}

export async function getAllScrapedLinks(
  venueIds: string[],
): Promise<string[]> {
  const links = (
    await Promise.all(
      venueIds.map(async (venueId) => {
        const venueSnap = await crawlerRef
          .where("venue.id", "==", venueId)
          .get();
        if (venueSnap.empty) {
          return [];
        }

        const venueLinks = venueSnap.docs.map((doc) => doc.id);
        return venueLinks;
      }),
    )
  ).flat();

  return links;
}

export async function hasLinkBeenScraped(link: string): Promise<boolean> {
  const linkDoc = await crawlerRef.doc(link).get();
  return linkDoc.exists;
}

export async function saveEventData(
  encodedLink: string,
  eventData: EventData,
): Promise<void> {
  const startTime = new Date(eventData.startTime);
  const endTime = new Date(eventData.endTime);
  const timestamp = new Date(eventData.crawlerInfo.timestamp);

  await crawlerRef.doc(encodedLink).set(
    {
      ...eventData,
      startTime: Timestamp.fromDate(startTime),
      endTime: Timestamp.fromDate(endTime),
      crawlerInfo: {
        ...eventData.crawlerInfo,
        timestamp: Timestamp.fromDate(timestamp),
      },
    },
    { merge: true },
  );
}

export async function buildDomainMap(venueUsernames: string[]): Promise<
  Record<
    string,
    {
      venue: UserModel;
      url: string;
    }
  >
> {
  const venues = await Promise.all(
    venueUsernames.map(async (username) => {
      const venueSnap = await usersRef.where("username", "==", username).get();
      if (venueSnap.empty) {
        throw new Error(`[!!!] no venue found for ${username}`);
      }

      const venueDoc = venueSnap.docs[0];
      const venue = venueDoc.data() as UserModel;
      return venue;
    }),
  );

  const domains = venues.map((venue) => {
    const rawWebsite = venue.venueInfo?.websiteUrl;
    const website = rawWebsite?.trim().startsWith("http")
      ? rawWebsite
      : `https://${rawWebsite}`;
    if (!website) {
      throw new Error(`[!!!] no website found for ${venue.username}`);
    }

    const domainName = getBaseDomain(website);
    return {
      domainName,
      venue,
      url: website,
    };
  });

  const domainMap: Record<string, { venue: UserModel; url: string }> = {};
  for (const { domainName, venue, url } of domains) {
    domainMap[domainName] = { venue, url };
  }

  return domainMap;
}

export async function groupByDayOfWeek(venueId: string) {
  const bookingsSnap = await bookingsRef
    .where("requesterId", "==", venueId)
    .where("status", "==", "confirmed")
    .get();

  const bookings = bookingsSnap.docs.map((doc) => doc.data() as Booking);
  const bookingsByDayOfWeek = Array.from({ length: 7 }, () => 0);

  for (const booking of bookings) {
    const date = booking.startTime.toDate();
    const dayOfWeek = date.getDay();
    if (dayOfWeek in bookingsByDayOfWeek) {
      bookingsByDayOfWeek[dayOfWeek] += 1;
    } else {
      bookingsByDayOfWeek[dayOfWeek] = 1;
    }
  }

  return bookingsByDayOfWeek;
}

export async function setBestDaysOfWeek(venueId: string) {
  const groups = await groupByDayOfWeek(venueId);
  await usersRef.doc(venueId).set(
    {
      venueInfo: {
        bookingsByDayOfWeek: groups,
      },
    },
    { merge: true },
  );
}

export async function getTopPerformersByVenueId(
  venueId: string,
  count: number = 5,
): Promise<string[]> {
  const venueBookingsSnap = await bookingsRef
    .where("requesterId", "==", venueId)
    .get();

  const venueBookings = venueBookingsSnap.docs.map((doc) => doc.data());

  const performerBookings: { [performerId: string]: number } = {};
  for (const booking of venueBookings) {
    const performerId = booking.requesteeId;
    if (performerId in performerBookings) {
      performerBookings[performerId] += 1;
    } else {
      performerBookings[performerId] = 1;
    }
  }

  const topPerformers = Object.entries(performerBookings)
    .sort((a, b) => b[1] - a[1])
    .slice(0, count)
    .map(([performerId]) => performerId);

  return topPerformers;
}

export async function setVenueTopPerformers({
  venueId,
  count = 5,
}: {
  venueId: string;
  count?: number;
}) {
  const performerIds = await getTopPerformersByVenueId(venueId, count);
  // const performers = await Promise.all(
  //   performerIds.map((id) => getUserById(id)),
  // );
  // console.log({ performers: performers.map((p) => p?.username) });
  await usersRef.doc(venueId).set(
    {
      venueInfo: {
        topPerformerIds: performerIds,
      },
    },
    { merge: true },
  );
}
