name: Flutter CI

on:
  push:
    branches: [main]
    paths:
      - 'pangolin/**'
  pull_request:
    branches: [main]
    paths:
      - 'pangolin/**'

jobs:
  flutter_test:
    name: Run Flutter Test and Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pangolin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    defaults:
      run:
        working-directory: pangolin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_android:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pangolin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - run: flutter build appbundle
