name: Rust

on:
  push:
    branches: [main]
    paths:
      - 'api.tapped.ai/**'
  pull_request:
    branches: [main]
    paths:
      - 'api.tapped.ai/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api.tapped.ai
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      # - name: Run tests
      #   run: cargo test --verbose
